[build]
  command = "npm run export"
  publish = "out"
  
[build.environment]
  NEXT_USE_NETLIFY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
